export const COUNTRIES = [
  "Afghanistan", "Afrique du Sud", "Albanie", "Algérie", "Allemagne", "Andorre", "Angola", "Antigua-et-Barbuda", 
  "Arabie Saoudite", "Argentine", "Arménie", "Australie", "Autriche", "Azerbaïdjan", "Bahamas", "Bahreïn", "Bangladesh", 
  "Barbade", "Belgique", "Belize", "Bénin", "Bhoutan", "Biélorussie", "Birmanie", "Bolivie", "Bosnie-Herzégovine", 
  "Botswana", "Brésil", "Brunei", "Bulgarie", "Burkina Faso", "Burundi", "Cameroun", "Canada", "Cap-Vert", "Chili", 
  "Chine", "Chypre", "Colombie", "Comores", "Congo-Brazzaville", "Congo-Kinshasa", "Corée du Nord", "Corée du Sud", 
  "Costa Rica", "Côte d'Ivoire", "Croatie", "Cuba", "Danemark", "Djibouti", "Dominique", "Égypte", "Émirats arabes unis", 
  "Équateur", "Érythrée", "Espagne", "Estonie", "Eswatini", "États-Unis", "Éthiopie", "Fidji", "Finlande", "France", 
  "Gabon", "Gambie", "Géorgie", "Ghana", "Grèce", "Grenade", "Guatemala", "Guinée", "Guinée-Bissau", "Guinée équatoriale", 
  "Guyana", "Haïti", "Honduras", "Hongrie", "Inde", "Indonésie", "Irak", "Iran", "Irlande", "Islande", "Israël", "Italie", 
  "Jamaïque", "Japon", "Jordanie", "Kazakhstan", "Kenya", "Kirghizistan", "Kiribati", "Koweït", "Laos", "Lesotho", "Lettonie", 
  "Liban", "Liberia", "Libye", "Liechtenstein", "Lituanie", "Luxembourg", "Macédoine du Nord", "Madagascar", "Malaisie", 
  "Malawi", "Maldives", "Mali", "Malte", "Maroc", "Maurice", "Mauritanie", "Mexique", "Micronésie", "Moldavie", "Monaco", 
  "Mongolie", "Monténégro", "Mozambique", "Namibie", "Nauru", "Népal", "Nicaragua", "Niger", "Nigeria", "Niue", "Norvège", 
  "Nouvelle-Zélande", "Oman", "Ouganda", "Ouzbékistan", "Pakistan", "Palaos", "Panama", "Papouasie-Nouvelle-Guinée", 
  "Paraguay", "Pays-Bas", "Pérou", "Philippines", "Pologne", "Portugal", "Qatar", "République centrafricaine", "République dominicaine", 
  "Roumanie", "Royaume-Uni", "Russie", "Rwanda", "Saint-Kitts-et-Nevis", "Saint-Marin", "Saint-Vincent-et-les-Grenadines", 
  "Sainte-Lucie", "Salvador", "Samoa", "São Tomé-et-Príncipe", "Sénégal", "Serbie", "Seychelles", "Sierra Leone", "Singapour", 
  "Slovaquie", "Slovénie", "Somalie", "Soudan", "Soudan du Sud", "Sri Lanka", "Suède", "Suisse", "Suriname", "Syrie", "Tadjikistan", 
  "Tanzanie", "Tchad", "Tchéquie", "Thaïlande", "Timor oriental", "Togo", "Tonga", "Trinité-et-Tobago", "Tunisie", "Turkménistan", 
  "Turquie", "Tuvalu", "Ukraine", "Uruguay", "Vanuatu", "Vatican", "Venezuela", "Viêt Nam", "Yémen", "Zambie", "Zimbabwe"
];

// Codes ISO 3166-1 alpha-2 officiels — un code unique par pays
export const COUNTRY_CODES = {
  "Afghanistan": "AF",
  "Afrique du Sud": "ZA",
  "Albanie": "AL",
  "Algérie": "DZ",
  "Allemagne": "DE",
  "Andorre": "AD",
  "Angola": "AO",
  "Antigua-et-Barbuda": "AG",
  "Arabie Saoudite": "SA",
  "Argentine": "AR",
  "Arménie": "AM",
  "Australie": "AU",
  "Autriche": "AT",
  "Azerbaïdjan": "AZ",
  "Bahamas": "BS",
  "Bahreïn": "BH",
  "Bangladesh": "BD",
  "Barbade": "BB",
  "Belgique": "BE",
  "Belize": "BZ",
  "Bénin": "BJ",
  "Bhoutan": "BT",
  "Biélorussie": "BY",
  "Birmanie": "MM",
  "Bolivie": "BO",
  "Bosnie-Herzégovine": "BA",
  "Botswana": "BW",
  "Brésil": "BR",
  "Brunei": "BN",
  "Bulgarie": "BG",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Cameroun": "CM",
  "Canada": "CA",
  "Cap-Vert": "CV",
  "Chili": "CL",
  "Chine": "CN",
  "Chypre": "CY",
  "Colombie": "CO",
  "Comores": "KM",
  "Congo-Brazzaville": "CG",
  "Congo-Kinshasa": "CD",
  "Corée du Nord": "KP",
  "Corée du Sud": "KR",
  "Costa Rica": "CR",
  "Côte d'Ivoire": "CI",
  "Croatie": "HR",
  "Cuba": "CU",
  "Danemark": "DK",
  "Djibouti": "DJ",
  "Dominique": "DM",
  "Égypte": "EG",
  "Émirats arabes unis": "AE",
  "Équateur": "EC",
  "Érythrée": "ER",
  "Espagne": "ES",
  "Estonie": "EE",
  "Eswatini": "SZ",
  "États-Unis": "US",
  "Éthiopie": "ET",
  "Fidji": "FJ",
  "Finlande": "FI",
  "France": "FR",
  "Gabon": "GA",
  "Gambie": "GM",
  "Géorgie": "GE",
  "Ghana": "GH",
  "Grèce": "GR",
  "Grenade": "GD",
  "Guatemala": "GT",
  "Guinée": "GN",
  "Guinée-Bissau": "GW",
  "Guinée équatoriale": "GQ",
  "Guyana": "GY",
  "Haïti": "HT",
  "Honduras": "HN",
  "Hongrie": "HU",
  "Inde": "IN",
  "Indonésie": "ID",
  "Irak": "IQ",
  "Iran": "IR",
  "Irlande": "IE",
  "Islande": "IS",
  "Israël": "IL",
  "Italie": "IT",
  "Jamaïque": "JM",
  "Japon": "JP",
  "Jordanie": "JO",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Kirghizistan": "KG",
  "Kiribati": "KI",
  "Koweït": "KW",
  "Laos": "LA",
  "Lesotho": "LS",
  "Lettonie": "LV",
  "Liban": "LB",
  "Liberia": "LR",
  "Libye": "LY",
  "Liechtenstein": "LI",
  "Lituanie": "LT",
  "Luxembourg": "LU",
  "Macédoine du Nord": "MK",
  "Madagascar": "MG",
  "Malaisie": "MY",
  "Malawi": "MW",
  "Maldives": "MV",
  "Mali": "ML",
  "Malte": "MT",
  "Maroc": "MA",
  "Maurice": "MU",
  "Mauritanie": "MR",
  "Mexique": "MX",
  "Micronésie": "FM",
  "Moldavie": "MD",
  "Monaco": "MC",
  "Mongolie": "MN",
  "Monténégro": "ME",
  "Mozambique": "MZ",
  "Namibie": "NA",
  "Nauru": "NR",
  "Népal": "NP",
  "Nicaragua": "NI",
  "Niger": "NE",
  "Nigeria": "NG",
  "Niue": "NU",
  "Norvège": "NO",
  "Nouvelle-Zélande": "NZ",
  "Oman": "OM",
  "Ouganda": "UG",
  "Ouzbékistan": "UZ",
  "Pakistan": "PK",
  "Palaos": "PW",
  "Panama": "PA",
  "Papouasie-Nouvelle-Guinée": "PG",
  "Paraguay": "PY",
  "Pays-Bas": "NL",
  "Pérou": "PE",
  "Philippines": "PH",
  "Pologne": "PL",
  "Portugal": "PT",
  "Qatar": "QA",
  "République centrafricaine": "CF",
  "République dominicaine": "DO",
  "Roumanie": "RO",
  "Royaume-Uni": "GB",
  "Russie": "RU",
  "Rwanda": "RW",
  "Saint-Kitts-et-Nevis": "KN",
  "Saint-Marin": "SM",
  "Saint-Vincent-et-les-Grenadines": "VC",
  "Sainte-Lucie": "LC",
  "Salvador": "SV",
  "Samoa": "WS",
  "São Tomé-et-Príncipe": "ST",
  "Sénégal": "SN",
  "Serbie": "RS",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Singapour": "SG",
  "Slovaquie": "SK",
  "Slovénie": "SI",
  "Somalie": "SO",
  "Soudan": "SD",
  "Soudan du Sud": "SS",
  "Sri Lanka": "LK",
  "Suède": "SE",
  "Suisse": "CH",
  "Suriname": "SR",
  "Syrie": "SY",
  "Tadjikistan": "TJ",
  "Tanzanie": "TZ",
  "Tchad": "TD",
  "Tchéquie": "CZ",
  "Thaïlande": "TH",
  "Timor oriental": "TL",
  "Togo": "TG",
  "Tonga": "TO",
  "Trinité-et-Tobago": "TT",
  "Tunisie": "TN",
  "Turkménistan": "TM",
  "Turquie": "TR",
  "Tuvalu": "TV",
  "Ukraine": "UA",
  "Uruguay": "UY",
  "Vanuatu": "VU",
  "Vatican": "VA",
  "Venezuela": "VE",
  "Viêt Nam": "VN",
  "Yémen": "YE",
  "Zambie": "ZM",
  "Zimbabwe": "ZW"
};
